### ISSUE TITLE
Unable to release finalizer for PVs created via legacy storage class

### ISSUE THREAD

**Issue by rfranzke** [kubernetes-csi/external-attacher#217]
The out-of-tree CSI drivers are still ([and forever?](https://kubernetes.slack.com/archives/CG04EL876/p1578500027013800?thread_ts=1578474999.005000&cid=CG04EL876)) compatible with the legacy (in-tree) provisioners, e.g. `kubernetes.io/aws-ebs`.
Provisioning + attaching a PV referencing such a storage class works perfectly fine with solely CSI. However, deleting such a volume is buggy as the external-attacher does not release its finalizer on the related `PersistentVolume` object.

It only watches for all `VolumeAttachment` and adds its finalizer to the referenced `PersistentVolume` on creation/update. However, when the PV gets deleted it checks whether `.spec.csi` is set which is not the case for a PV using a legacy provisioner. It correctly detaches the volume and releases the `VolumeAttachment`, though, the `PersistentVolume` will stuck forever in the system.

The culprit function seems to be https://github.com/kubernetes-csi/external-attacher/blob/2d2ab15c96d6b22e9fb7c290b22bafa8d2cee4e1/pkg/controller/controller.go#L219-L224

/kind bug

**Comment by rfranzke** [comment]
Steps for reproduction:

1. Create a Kubernetes cluster and install the necessary CSI controllers into it.
1. Create a `StorageClass` with a legacy provisioner:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
3. Create a `PersistentVolumeClaim` referencing it and a `Pod`:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: app3
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim3
```

4. See the volume being correctly provisioned and attached. The external-attacher adds its finalizer correctly to both `VolumeAttachment` and `PersistentVolume` objects.
1. Delete the PVC and the pod again.
1. See the volume being correctly detached and deprovisioned/deleted from the infrastructure. However, observe that the the `PersistentVolume` is stuck in `Terminating` state as the finalizer of the external-attacher is still present.
